---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jaeger-selector
  template:
    metadata:
      labels:
        component: jaeger-selector
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "16686"  
    spec:
      containers:
          -   env:
              - name: COLLECTOR_ZIPKIN_HTTP_PORT
                value: "9411"
              image: jaegertracing/all-in-one
              name: jaeger
              ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: 16686
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 14269
                initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
   name: jaeger-query
spec:
   type: LoadBalancer
   selector:
      component: jaeger-selector
   ports:
      - name: query-http
        port: 80
        protocol: TCP
        targetPort: 16686
---
apiVersion: v1
kind: Service
metadata:
   name: jaeger-collector
spec:
   type: ClusterIP
   selector:
      component: jaeger-selector
   ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
      
      
---
apiVersion: v1
kind: Service
metadata:
   name: zipkin
spec:
   selector:
      component: jaeger-selector
   ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411   


---
apiVersion: v1
kind: Service
metadata:
   name: jaeger-agent
spec:
   selector:
      component: jaeger-selector
   ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831  
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832 
    - name: agent-configs
      port: 5778
      protocol: TCP
      targetPort: 5778  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: database-persistent-volume-claim
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql-selector
  template:
    metadata:
      labels:
        component: mysql-selector
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: ordersDB
            - name: MYSQL_USER
              value: myuser             
            - name: MYSQL_PASSWORD
              value: mypass             
            - name: MYSQL_ROOT_PASSWORD
              value: myrootpass    
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
   name: mysql-cluster-ip-service
spec:
   type: ClusterIP
   selector:
      component: mysql-selector
   ports:
   -  port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: user-service-selector
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user-service-selector
  template:
    metadata:
      labels:
        component: user-service-selector
    spec:
      containers:
      - image: deepakjain01/user-service
        name: user-service
        env:
          - name: RDS_HOST
            value: mysql-cluster-ip-service
          - name: JAEGER_QUERY_API_URL
            value: http://jaeger-query
          - name: JAEGER_COLLECTOR_API_URL
            value: http://jaeger-collector               
---
apiVersion: v1
kind: Service
metadata:
  name: user-cluster-ip-service
spec:
  selector:
    component: user-service-selector
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: orders-service-selector
  name: orders-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orders-service-selector
  template:
    metadata:
      labels:
        component: orders-service-selector
    spec:
      containers:
      - image: deepakjain01/orders-service
        name: orders-service
        env:
          - name: JAEGER_QUERY_API_URL
            value: http://jaeger-query
          - name: JAEGER_COLLECTOR_API_URL
            value: http://jaeger-collector                 
---
apiVersion: v1
kind: Service
metadata:
  name: orders-cluster-ip-service
spec:
  selector:
    component: orders-service-selector
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: aggregator-service-selector
  name: aggregator-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: aggregator-service-selector
  template:
    metadata:
      labels:
        component: aggregator-service-selector
    spec:
      containers:
      - image: deepakjain01/aggregator-service
        name: aggregator-service
        env:
          - name: USER_SERVICE_URI
            value: http://user-cluster-ip-service:8081  
          - name: ORDERS_SERVICE_URI
            value: http://orders-cluster-ip-service:8082     
          - name: JAEGER_QUERY_API_URL
            value: http://jaeger-query
          - name: JAEGER_COLLECTOR_API_URL
            value: http://jaeger-collector          
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-cluster-ip-service
spec:
  selector:
    component: aggregator-service-selector
  type: ClusterIP
  ports:
  - port: 8080 
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: aggregator-cluster-ip-service
              servicePort: 8080



