version: '3.7'
services:
   mysql-db:
      image: mysql:5.7
      container_name: mysql-db
      ports:
      - "3306:3306"
      restart: always
      environment:
         MYSQL_DATABASE: ordersDB
         MYSQL_USER: myuser
         MYSQL_PASSWORD: mypass
         MYSQL_ROOT_PASSWORD: myrootpass
      volumes:
      - dbdata:/var/lib/mysql
      networks:
      - dockr-net
   user-service:
#image: deepakjain01/user-service:latest
      build:
         dockerfile: Dockerfile
         context: ./user-service
      container_name: user-service
      ports:
      - "8081:8081"
      restart: always
      environment:
         RDS_HOST: mysql-db
      depends_on:
      - mysql-db
      networks:
      - dockr-net
   orders-service:
#image: deepakjain01/orders-service:latest
      build:
         dockerfile: Dockerfile
         context: ./orders-service
      container_name: orders-service
      ports:
      - "8082:8082"
      restart: always
      networks:
      - dockr-net
   aggregator-service:
#image: deepakjain01/aggregator-service:latest
      build:
         dockerfile: Dockerfile
         context: ./aggregator-service
      container_name: aggregator-service
      ports:
      - "8080:8080"
      restart: always
      environment:
         USER_SERVICE_URI: http://user-service:8081
         ORDERS_SERVICE_URI: http://orders-service:8082
      depends_on:
      - user-service
      - orders-service
      networks:
      - dockr-net
volumes:
   dbdata: 
networks:
   dockr-net: 